<Project>
    <PropertyGroup>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="AwesomeAssertions" Version="9.6.0"/>
        <PackageVersion Include="ClosedXML" Version="0.105.1"/>
        <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.10.0"/>
        <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23"/>
        <PackageVersion Include="morelinq" Version="4.4.0"/>
        <PackageVersion Include="Nerdbank.GitVersioning" Version="3.10.94"/>
        <PackageVersion Include="Nerdbank.MessagePack" Version="1.3.85"/>
        <PackageVersion Include="NorthSouthSystems.MessagePackable" Version="1.1.12-beta"/>
        <!-- NorthSouthSystems.Opinions.BCL: Run the T4 template to update! -->
        <PackageVersion Include="NorthSouthSystems.Text" Version="8.0.1"/>
        <!-- This is NOT a Microsoft package; it is from ZZZ Projects. -->
        <PackageVersion Include="System.Linq.Dynamic.Core" Version="1.7.3"/>
        <PackageVersion Include="Verify.XunitV3" Version="32.0.0"/>
        <PackageVersion Include="xunit.v3" Version="4.0.0"/>

        <!-- Transitive Pinning -->
        <!-- This will help prevent large(r) potentially breaking version bumps, and it will also -->
        <!-- allow us to benefit from potential performance improvements to newer package versions. -->
        <!-- In some cases, transitive pinning is necessary due to an unexplicable error, likely related to -->
        <!-- explicit nuget.config package mapping (which we have since relaxed with a catch-all pattern): -->
        <!-- NU1102 "Unable to find package ... with version (>= [a valid version])" -->

        <!-- ClosedXML -->
        <!-- Regarding SixLabors.Fonts: https://github.com/ClosedXML/ClosedXML/releases/tag/0.105.1 -->
        <PackageVersion Include="DocumentFormat.OpenXml" Version="3.5.1"/>
        <PackageVersion Include="SixLabors.Fonts" Version="[2.1.3,3.0.0)"/>

        <!-- Nerdbank.MessagePack -->
        <PackageVersion Include="PolyType" Version="1.4.1"/>
    </ItemGroup>
</Project>
